version: '3.8'

services:
  db_amt_auth:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-amt_auth}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-amt}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-amt}
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: