name: Push workflow
on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Copy keys
        working-directory: .
        shell: bash
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
          PUBLIC_KEY: ${{ secrets.PUBLICKEY }}
        run: 
          echo "$PRIVATE_KEY" > privateKey.pem && echo "$PUBLIC_KEY" > publicKey.pem
      - name: Install the dependencies
        working-directory: .
        run: mvn clean install -DskipTests=true
      - name: Run the tests
        run: mvn test
